watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start --whkd"
bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    animation:
      enabled: true
      duration: 800
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      round_corners_type: "normal" 
      border_color: none
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 33
    padding:
      top: 5
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        [
          "glazewm_workspaces",
          "komorebi_workspaces",
          "komorebi_active_layout",
          "active_window"
        ]
      center:
        [
          "clock",
        ]
      right:
        [
          "media",
          "volume",
          "wifi",
          "wallpaper",
          "power_menu",
        ]
      
widgets:
  bin:
    type: "yasb.recycle_bin.RecycleBinWidget"
    options:
      label: "<span>{icon}</span> {items_size}"
      label_alt: "{items_coun t} ({items_size})"
      icons:
        bin_empty: "\udb82\ude7a"
        bin_filled: "\udb82\ude79"
      callbacks:
        on_left: "open_bin"
        on_right: "do_nothing"
        on_middle: "empty_bin"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: false
      hide_if_offline: true
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
      animation: true
      enable_scroll_switching: true
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "komorebi offline"
      label_float_override: "floating tiles"
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "\udb81\udc3e"
      label_workspace_populated_btn: "\udb81\udc3e"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true
      toggle_workspace_layer:
        enabled: false
        tiling_label: "Tiling"
        floating_label: "Floating"
      app_icons: 
        enabled_populated: false
        enabled_active: false
        size: 12
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 15
        color: "#000000"
  wallpaper:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
      label: "<span>\uf03e</span>"
      image_path: "%USERPROFILE%\\Documents\\all\\wallpapers"
      change_automatically: false # Automatically change wallpaper
      update_interval: 60        
      gallery: 
        enabled: true
        blur: true
        image_width: 250
        image_per_page: 4
        show_buttons: true
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: true
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "▼"
      label_expanded: "▶"
      label_position: "left" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: true
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 1
      reverse: 0
      foreground: "#91d7e3"
      gradient_color_1: '#91d7e3'
      gradient_color_2: '#8aadf4'
      bars_number: 14
      bar_spacing: 2
      bar_width: 5
      noise_reduction: 0.20
      sleep_timer: 2
      hide_empty: false
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 4
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "C:\\Users\\HP\\Downloads"}
        - { title: "Documents", path: "C:\\Users\\HP\\Documents"}
        - { title: "Pictures", path: "C:\\Users\\HP\\Pictures"}
        - { title: "Videos", path: "C:\\Users\\HP\\Videos"}
      system_menu: true

      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: ""
      distance: 10
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: " <span>\uf001</span> {title}"
      label_alt: " <span>\uf001</span> {title}"
      hide_empty: true
      callbacks:
       on_left: "toggle_media_menu"
       on_middle: "do_nothing"
       on_right: "toggle_label"
      max_field_size:
        label: 50
        label_alt: 50
      show_thumbnail: false
      controls_only: false
      controls_left: true
      thumbnail_alpha: 50
      thumbnail_padding: 0
      thumbnail_corner_radius: 8
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
       blur: true
       round_corners: true
       round_corners_type: "normal"
       border_color: "#45475a"
       alignment: "right"
       direction: "down"
       offset_top: 5
       offset_left: 0
       thumbnail_corner_radius: 8
       thumbnail_size: 100
       max_title_size: 80
       max_artist_size: 20
       show_source: true
       show_volume_slider: true            # Whether to show the volume slider in the popup. Volume control per application.
      media_menu_icons:
       play: "\ue768"
       pause: "\ue769"
       prev_track: "\ue892"
       next_track: "\ue893"
      icons:
       prev_track: "\uf048"
       next_track: "\uf051"
       play: "\uf04b"
       pause: "\uf04c"
      container_shadow: 
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span> {%a %b %d | %I:%M %p}" 
      label_alt: "{%a %b %d %I:%M %p %Z}"
      timezones: [] #Looking up time zone info from registry
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"  
      calendar:
        alignment: "center"
        show_holidays: true
        holiday_color: "#f38ba8"

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{layout_name}"
      layouts: ['bsp', 'columns', 'rows', 'grid', 'scrolling', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        scrolling: "\uebf7"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        monocle: "\uf06f"
        maximized: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      callbacks:
        on_left: 'toggle_layout_menu'
        on_middle: 'next_layout'
        on_right: 'prev_layout'
      layout_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icons: true
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]      
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: '05e7947190a74c58a3c231423251110'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: "Sparta, New Jersey"
      units: "imperial"
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\ue3c2"
        cloudyDay: "\ue21d"
        cloudyNight: "\ue226"
        rainyDay: "\ue371"
        rainyNight: "\ue371"
        snowyIcyDay: "\udb81\udf17"
        snowyIcyNight: "\udb81\udf17"
        blizzardDay: "\udb81\udd99"
        default: "\udb81\udd99"
      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "#45475a"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 48
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" 
        - "\uf026"
        - "\uf027" 
        - "\uf027"  
        - "\uf028"
      audio_menu:
        blur: False
        round_corners: True
        round_corners_type: 'normal'
        border_color: '#cdd6f4'
        alignment: 'right'
        direction: 'down'
        distance: 6
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "exec cmd.exe /c start ms-settings:sound"
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
      tooltip: False

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "<span>\uf011</span>"
      uptime: True
      blur: true

      blur_background: true
      animation_duration: 250
      button_row: 3
      buttons:
        signout: ["\udb80\udf43","Sign out"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        sleep: ["\udb82\udd04","Sleep"]
        lock: ["\uf023","Lock"]
        cancel: ["\udb81\udf3a","Cancel"]
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      tooltip: true
      show_only_visible: false
      strict_filtering: true
      monitor_exclusive: false
      animation:
        enabled: true
      preview:
        enabled: true
        width: 240
        delay: 400
        padding: 8
        margin: 8
      title_label:
        enabled: true
        show: "focused"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}"
      label_no_window: ""
      
      label_icon: true
      label_icon_size: 14
      max_length: 20
      max_length_ellipsis: "..."
      monitor_exclusive: true
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
  komorebi_control:
    type: "komorebi.control.KomorebiControlWidget"
    options:
      label: "<span>\udb80\uddd9</span>"
      icons:
        start: "\uead3"
        stop: "\uead7"
        reload: "\uead2"
      run_ahk: false
      run_whkd: true
      show_version: true
      komorebi_menu:
        blur: false
        round_corners: true
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'left'
        direction: 'down'
        offset_top: 6
        offset_left: 0
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"

  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
      image_path: "C:\\Users\\HP\\Pictures\\Wallpapers" # Example path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds
      gallery:
        enabled: true
        blur: false
        image_width: 200
        image_per_page: 8
        show_buttons: true
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: true
   
  
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
      label: "<span>\uf473</span>"
      label_alt: "<span>\uf473</span>"
      group_label:
        volume_labels: ["C", "D", "E", "F"]
        show_label_name: true 
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        distance: 6
      callbacks:
        on_left: "toggle_group"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 5
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd.exe /c Taskmgr"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 0
  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        container_shadow:
          enabled: false
          offset: [0, 0]
          radius: 10      
          color: "#000000"
        label: "<span>{wifi_icon}</span>"
        label_alt: "{wifi_name} {wifi_strength}%"
        update_interval: 5000
        callbacks:
          on_left: "exec cmd.exe /c explorer ms-availablenetworks:"
          on_middle: "do_nothing"
          on_right: "toggle_label"
        container_padding:
          top: 0
          left: 0
          bottom: 0
          right: 0
        wifi_icons: [
          "\udb82\udd2e",  # Icon for 0% strength
          "\udb82\udd1f",  # Icon for 1-20% strength
          "\udb82\udd22",  # Icon for 21-40% strength
          "\udb82\udd25",  # Icon for 41-80% strength
          "\udb82\udd28"   # Icon for 81-100% strength
        ]
  update_check:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 180
        exclude: []
      windows_update:
        enabled: false
        label: "<span>\uf0ab</span>{count}"
        interval: 240
        exclude: []
  notes:
    type: "yasb.notes.NotesWidget"
    options:
      label: "<span>\udb82\udd0c</span> {count}"
      label_alt: "{count} notes"
      container_shadow:
        enabled: false
        offset: [0, 0]
        radius: 10
        color: "#000000"
    container_padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    menu:
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      alignment: "right"
      direction: "down"
      offset_top: 6
      offset_left: 0
      max_title_size: 100
      show_date_time: true
    icons:
      note: "\udb82\udd0c"
      delete: "\ue20d"
    callbacks:
      on_left: "toggle_menu"
      on_middle: "do_nothing"
      on_right: "toggle_label"
      

